name: Terraform Apply v2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      run_apply:
        description: Select this only if you want to run terraform apply 
        type: boolean
        required: false
        default: false
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.SECRET_PRIME }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: My First Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.MY_TERRAFORM_LOGIN_TOKEN }}
      
      - name: Run Terraform Init
        run: terraform init

      - name: Check Terraform Format
        run: terraform fmt -check -recursive

      - name: Run Terraform Plan
        run: terraform plan

      - name: Run Terraform Apply 
        run: terraform apply -auto-approve
        if: ${{ github.event.inputs.run_apply }}